name: Build and Push Image to ECR

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - releases/**

jobs:
  build-and-push:
    if: "!startsWith(github.event.head_commit.message, 'Initial commit')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_BUILD_ROLE }}
          role-session-name: GitHubWorkflow

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_URL }}:$IMAGE_TAG .
          docker build -t ${{ vars.ECR_REPOSITORY_URL }}:latest .
          docker push ${{ vars.ECR_REPOSITORY_URL }}:$IMAGE_TAG
          docker push ${{ vars.ECR_REPOSITORY_URL }}:latest
