name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!startsWith(github.event.head_commit.message, 'Initial commit')"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_DEPLOY }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Register ECS Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-register-task-definition@v2
        with:
          family: ${{ env.ECS_TASK_DEFINITION }}
          container-definitions: |
            [
              {
                "name": "${{ github.event.repository.name }}",
                "image": "${{ env.ECR_REGISTRY_URL }}:${{ github.sha }}",
                "essential": true,
                "memory": 512,
                "cpu": 256,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ]

      - name: Deploy to ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          task-definition: ${{ steps.task-def.outputs.task-definition-arn }}
          wait-for-service-stability: true